version: '3.7'

networks:
  mynet:
    external: true

services:

  logspout:
    image: registry.datacommand.co.kr/cdm-cloud-logspout:<tag>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      syslog+tcp://cdm-cloud-monitor:514
    networks:
      - mynet
    deploy:
      mode: global
